### ISSUE TITLE
MRSea package 

### ISSUE THREAD

**Issue by lindesaysh** [dmpstats/Behavioural_Classification_for_Vultures#7]
`library(MRSea)` is required for the speed time threshold calculation.  

Query how moveapps will load this package as it is installed from github

The library can be found here
`devtools::[install_github](https://remotes.r-lib.org/reference/install_github.html)("lindesaysh/MRSea", ref="stable")`

**Comment by bcaneco** [comment]
Here's the reply from Andrea:

"Hi Bruno,
Installing R packages from github or gitlab is absolutely no problem, we have done it often. Just important that you point out the github link in your (first) version description of the App at submission, then I can update the docker file. This is not automatic (yet), but I can do this small step manually."

So, all good!
